// src/app/components/modals/dish-detail-modal.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MenuItem } from '../../models/models';
import { CartService } from '../../services/cart.service';

@Component({
  selector: 'app-dish-detail-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div *ngIf="isOpen && dish" class="modal-overlay" (click)="onBackdropClick($event)">
      <div class="modal-card dish-detail-card" (click)="$event.stopPropagation()">
        <button class="modal-close-btn" (click)="closeModal()" aria-label="Close modal">
          <svg width="20" height="20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
          </svg>
        </button>

        <div class="dish-detail-grid">
          <div class="dish-detail-image-wrapper">
            <img [src]="dish.image" [alt]="dish.name" class="dish-detail-img" />
            <span *ngIf="dish.isChefSpecial" class="chef-badge-overlay">Chef's Choice</span>
          </div>

          <div class="dish-detail-info">
            <div class="dish-header-row">
              <span class="diet-pill" [class.veg]="dish.diet === 'Veg'" [class.non-veg]="dish.diet === 'Non-Veg'">
                {{ dish.diet }}
              </span>
              <span class="category-pill">{{ dish.category }}</span>
              <span *ngIf="dish.rating" class="rating-pill">★ {{ dish.rating }}</span>
            </div>

            <h2 class="dish-title">{{ dish.name }}</h2>
            <p class="dish-price">₹{{ dish.price }}</p>
            
            <p class="dish-description">{{ dish.description }}</p>

            <div class="spicy-level-row" *ngIf="dish.spicyLevel > 0">
              <span class="spicy-label">Spiciness:</span>
              <div class="chili-icons">
                <span *ngFor="let c of [].constructor(dish.spicyLevel)" class="chili-icon">🌶️</span>
              </div>
            </div>

            <div class="quantity-add-container">
              <div class="quantity-selector">
                <button type="button" (click)="decreaseQty()" [disabled]="quantity <= 1" class="qty-btn">-</button>
                <span class="qty-val">{{ quantity }}</span>
                <button type="button" (click)="increaseQty()" class="qty-btn">+</button>
              </div>

              <button class="btn btn-primary add-to-cart-btn" (click)="handleAddToCart()">
                Add to Order • ₹{{ dish.price * quantity }}
              </button>
            </div>

            <div *ngIf="addedSuccess" class="added-toast">
              Added {{ quantity }}x {{ dish.name }} to your cart!
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .modal-overlay {
      position: fixed;
      inset: 0;
      background: rgba(10, 8, 20, 0.85);
      backdrop-filter: blur(12px);
      z-index: 1000;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1.5rem;
      animation: fadeIn 0.25s ease-out;
    }

    .dish-detail-card {
      background: var(--bg-card);
      border: 1px solid var(--border-color);
      border-radius: var(--radius-lg);
      max-width: 820px;
      width: 100%;
      overflow: hidden;
      position: relative;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.7);
    }

    .modal-close-btn {
      position: absolute;
      top: 1rem;
      right: 1rem;
      z-index: 10;
      background: rgba(15, 23, 42, 0.75);
      border: 1px solid rgba(255, 255, 255, 0.15);
      color: var(--text-muted);
      width: 36px;
      height: 36px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      transition: var(--transition-fast);
    }

    .modal-close-btn:hover {
      color: #fff;
      background: rgba(239, 68, 68, 0.8);
      border-color: transparent;
    }

    .dish-detail-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
    }

    @media (max-width: 768px) {
      .dish-detail-grid {
        grid-template-columns: 1fr;
      }
    }

    .dish-detail-image-wrapper {
      position: relative;
      height: 100%;
      min-height: 300px;
      background: var(--bg-surface);
    }

    .dish-detail-img {
      width: 100%;
      height: 100%;
      object-fit: cover;
    }

    .chef-badge-overlay {
      position: absolute;
      bottom: 1rem;
      left: 1rem;
      background: linear-gradient(135deg, var(--gold-accent), var(--gold-hover));
      color: #0d0b18;
      font-weight: 700;
      font-size: 0.75rem;
      padding: 0.35rem 0.85rem;
      border-radius: 20px;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }

    .dish-detail-info {
      padding: 2.25rem 2rem;
      display: flex;
      flex-direction: column;
      justify-content: center;
    }

    .dish-header-row {
      display: flex;
      align-items: center;
      gap: 0.6rem;
      margin-bottom: 0.75rem;
    }

    .diet-pill {
      font-size: 0.75rem;
      font-weight: 700;
      padding: 0.2rem 0.6rem;
      border-radius: 4px;
      text-transform: uppercase;
    }

    .diet-pill.veg {
      background: rgba(34, 197, 94, 0.15);
      color: #4ade80;
      border: 1px solid rgba(34, 197, 94, 0.3);
    }

    .diet-pill.non-veg {
      background: rgba(239, 68, 68, 0.15);
      color: #f87171;
      border: 1px solid rgba(239, 68, 68, 0.3);
    }

    .category-pill {
      font-size: 0.75rem;
      color: var(--text-muted);
      background: rgba(255, 255, 255, 0.05);
      padding: 0.2rem 0.6rem;
      border-radius: 4px;
    }

    .rating-pill {
      font-size: 0.75rem;
      color: #fbbf24;
      background: rgba(251, 191, 36, 0.1);
      padding: 0.2rem 0.5rem;
      border-radius: 4px;
      margin-left: auto;
    }

    .dish-title {
      font-family: 'Cinzel', serif;
      font-size: 1.75rem;
      color: var(--text-light);
      margin-bottom: 0.5rem;
    }

    .dish-price {
      font-size: 1.5rem;
      font-weight: 700;
      color: var(--primary-accent);
      margin-bottom: 1rem;
    }

    .dish-description {
      color: var(--text-muted);
      line-height: 1.6;
      font-size: 0.95rem;
      margin-bottom: 1.25rem;
    }

    .spicy-level-row {
      display: flex;
      align-items: center;
      gap: 0.5rem;
      margin-bottom: 1.5rem;
    }

    .spicy-label {
      font-size: 0.85rem;
      color: var(--text-muted);
    }

    .quantity-add-container {
      display: flex;
      align-items: center;
      gap: 1rem;
      margin-top: 0.5rem;
    }

    .quantity-selector {
      display: flex;
      align-items: center;
      background: var(--bg-surface);
      border: 1px solid var(--border-color);
      border-radius: var(--radius-md);
      overflow: hidden;
    }

    .qty-btn {
      background: transparent;
      border: none;
      color: var(--text-light);
      width: 38px;
      height: 38px;
      font-size: 1.2rem;
      cursor: pointer;
      transition: var(--transition-fast);
    }

    .qty-btn:hover:not(:disabled) {
      background: rgba(255, 255, 255, 0.1);
    }

    .qty-btn:disabled {
      opacity: 0.3;
      cursor: not-allowed;
    }

    .qty-val {
      width: 32px;
      text-align: center;
      font-weight: 700;
      color: var(--text-light);
    }

    .add-to-cart-btn {
      flex: 1;
      padding: 0.75rem 1rem;
      font-size: 0.95rem;
    }

    .added-toast {
      margin-top: 1rem;
      background: rgba(34, 197, 94, 0.15);
      border: 1px solid rgba(34, 197, 94, 0.3);
      color: #4ade80;
      padding: 0.6rem;
      border-radius: var(--radius-sm);
      font-size: 0.85rem;
      text-align: center;
      animation: fadeIn 0.2s ease;
    }

    @keyframes fadeIn {
      from { opacity: 0; transform: scale(0.97); }
      to { opacity: 1; transform: scale(1); }
    }
  `]
})
export class DishDetailModalComponent implements OnChanges {
  @Input() dish: MenuItem | null = null;
  @Input() isOpen: boolean = false;
  @Output() close = new EventEmitter<void>();

  quantity: number = 1;
  addedSuccess: boolean = false;

  constructor(private cartService: CartService) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['dish'] || changes['isOpen']) {
      this.quantity = 1;
      this.addedSuccess = false;
    }
  }

  increaseQty(): void {
    this.quantity++;
  }

  decreaseQty(): void {
    if (this.quantity > 1) {
      this.quantity--;
    }
  }

  handleAddToCart(): void {
    if (!this.dish) return;
    this.cartService.addToCart(this.dish, this.quantity);
    this.addedSuccess = true;
    setTimeout(() => {
      this.addedSuccess = false;
      this.closeModal();
    }, 1000);
  }

  closeModal(): void {
    this.close.emit();
  }

  onBackdropClick(event: MouseEvent): void {
    this.closeModal();
  }
}

// src/components/Modals/DishDetailModal.jsx
import React, { useState } from 'react';
import { X, Flame, Plus, Minus, Star, Sparkles, ShoppingBag } from 'lucide-react';

export default function DishDetailModal({ dish, onClose, onAddToCart }) {
  const [qty, setQty] = useState(1);
  const [added, setAdded] = useState(false);

  if (!dish) return null;

  const handleAdd = () => {
    onAddToCart({ ...dish, quantity: qty });
    setAdded(true);
    setTimeout(() => {
      setAdded(false);
      onClose();
    }, 800);
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-content" onClick={e => e.stopPropagation()} style={{ maxWidth: '600px', overflow: 'hidden' }}>
        
        {/* IMAGE BANNER WITH CLOSE BUTTON */}
        <div style={{ position: 'relative', height: '280px' }}>
          <img src={dish.image} alt={dish.name} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
          <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(28,28,28,1) 0%, transparent 60%)' }} />
          
          <button
            onClick={onClose}
            style={{
              position: 'absolute',
              top: '16px',
              right: '16px',
              background: 'rgba(13,13,13,0.7)',
              backdropFilter: 'blur(8px)',
              border: 'none',
              color: 'var(--white)',
              width: '36px',
              height: '36px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              cursor: 'pointer'
            }}
          >
            <X size={20} />
          </button>

          <div style={{ position: 'absolute', bottom: '20px', left: '24px', right: '24px', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end' }}>
            <div>
              <div style={{ display: 'flex', gap: '8px', marginBottom: '6px' }}>
                <span className={`badge-diet ${dish.diet === 'Veg' ? 'badge-veg' : 'badge-nonveg'}`}>
                  {dish.diet}
                </span>
                {dish.isChefSpecial && (
                  <span className="badge-diet badge-chef">
                    <Sparkles size={10} /> Royal Special
                  </span>
                )}
              </div>
              <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '26px', color: 'var(--white)', fontWeight: '500' }}>
                {dish.name}
              </h2>
            </div>

            <div style={{ fontFamily: 'var(--font-display)', fontSize: '26px', color: 'var(--gold)', fontWeight: '600' }}>
              ₹{dish.price}
            </div>
          </div>
        </div>

        {/* DETAILS BODY */}
        <div style={{ padding: '24px 28px' }}>
          <p style={{ fontSize: '14px', lineHeight: '1.7', color: 'rgba(255,255,255,0.75)', marginBottom: '20px' }}>
            {dish.description}
          </p>

          <div style={{ background: 'var(--dark3)', border: '1px solid rgba(255,255,255,0.08)', padding: '16px', borderRadius: '4px', display: 'flex', flexDirection: 'column', gap: '10px', fontSize: '12px', color: 'rgba(255,255,255,0.7)', marginBottom: '24px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: 'var(--gray-light)' }}>Culinary Style:</span>
              <strong style={{ color: 'var(--gold)' }}>Contemporary Hyderabadi Fine Dining</strong>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: 'var(--gray-light)' }}>Spice Profile:</span>
              <span style={{ color: 'var(--white)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                {Array.from({ length: dish.spicyLevel || 0 }).map((_, i) => (
                  <Flame key={i} size={12} color="#ef4444" fill="#ef4444" />
                ))}
                {dish.spicyLevel === 0 ? 'Mild & Fragrant' : `Level ${dish.spicyLevel} Heat`}
              </span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ color: 'var(--gray-light)' }}>Preparation Method:</span>
              <span style={{ color: 'var(--white)' }}>Freshly slow-simmered over white wood ash</span>
            </div>
          </div>

          {/* QUANTITY AND ADD TO CART */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', background: 'var(--dark3)', border: '1px solid rgba(255,255,255,0.1)', padding: '10px 16px', borderRadius: '4px' }}>
              <button onClick={() => setQty(Math.max(1, qty - 1))} style={{ color: 'var(--white)' }}>
                <Minus size={16} />
              </button>
              <span style={{ fontFamily: 'var(--font-display)', fontSize: '16px', fontWeight: '600', color: 'var(--gold)', minWidth: '20px', textAlign: 'center' }}>
                {qty}
              </span>
              <button onClick={() => setQty(qty + 1)} style={{ color: 'var(--white)' }}>
                <Plus size={16} />
              </button>
            </div>

            <button
              onClick={handleAdd}
              className="btn btn-primary"
              style={{ flex: 1, padding: '14px', fontSize: '11px' }}
            >
              <ShoppingBag size={15} />
              <span>{added ? 'Added to Order!' : `Add to Order (₹${dish.price * qty})`}</span>
            </button>
          </div>

        </div>

      </div>
    </div>
  );
}
